language: node_js
node_js:
- lts/*
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: 
        - npm run build
        - mv build sergate
        - zip -r -9 -m sergate.zip ./sergate -x .gitignore
      deploy:
        provider: script
        skip_cleanup: true
        script:
        - npx semantic-release